### PR TITLE
Remove using namespace std

### PR DESCRIPTION
**Pull request by bwalden**
This PR removes the using namespace std from ptlib/contain.h. Addressing compilation issues with C++20 on Windows where std::byte conflicts with Microsoft's definition of byte.

### CODE REVIEW

**Comment by willamowius** [comment]
Thanks for the patch, but isn't there a fix for the Microsoft incompatibility that doesn't change almost every file ? The code base is 20 years old and this change would make it very difficult to compare with old code.

**Comment by bwalden** [comment]
Although large, the diff should be relatively trivial. Other than msos/ptlib/contain.h and unix/ptlib/contain.h, the only real changes are to prefix STL typenames with 'std::'.

An alternative would have been to add using statements to ptlib/contain.h for every unscoped STL typename used in ptlib. This would then require C++17 to compile ptlib. Although it would have produced a smaller diff, it felt like a more impactful and less desirable change.

**Comment by willamowius** [comment]
I just tried in an old VM with VS2019 16.4.3 and PTLib compiled without a code change. Which version are you using ?

**Comment by bwalden** [comment]
I'm using VS2022 17.7.6. I've attached a demo project to show the problem.
[ptlib-demo.zip](https://github.com/willamowius/ptlib/files/13252856/ptlib-demo.zip)

**Comment by willamowius** [comment]
The easiest solution would be to switch your project to C++14. std::byte was introduced in C++17.

**Comment by bwalden** [comment]
Whilst switching downstream projects to C++14 does work around the problem, it is hardly a solution.

In my use-case the downstream projects rely heavily on C++17 and C++20 features.

Happy to close the PR and use the fork if this change will not benefit others.

**Comment by willamowius** [comment]
Yes, I believe others will be better served by keeping the source stable.
Please don't let this discourage you from submitting other pull requests.

**Pull request closed without merging**
