### PR TITLE
Add missing macros so that autoconf can be regenerated

### PR DESCRIPTION
**Pull request by brad0**
Right now the autoconf script cannot be regenerated due to some missing macros.

configure.ac:17: error: possibly undefined macro: dnl
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:187: error: possibly undefined macro: AC_DEFINE

aclocal generates the minimal macros necessary to resolve the issue.

### CODE REVIEW

**Comment by willamowius** [comment]
In what situation do you get the mentioned error message ?

Also, your pull request seems incomplete. You seem to have made other changes to configure.ac, eg. renaming OPENSSL and SDL to lowercase (which I don't really like).

**Comment by brad0** [comment]
> In what situation do you get the mentioned error message ?
> 
> Also, your pull request seems incomplete. You seem to have made other changes to configure.ac, eg. renaming OPENSSL and SDL to lowercase (which I don't really like).

When you try to regenerate the autoconf script.

I didn't make any other changes. That is the proper auto-generated form with the macros being used as is.

What else is necessary for the PR?

**Comment by willamowius** [comment]
Running "autoconf" to regenerate configure works fine when I try it. I don't see the issue, yet.

**Comment by willamowius** [comment]
Added aclocal.m4

**Pull request closed without merging**
